name: bestfranchise
description: bestfranchise
version: 1.0.0+1
environment:
#  sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2+4
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.0
  flutter_screen_scaler: ^2.0.0
  http: ^0.12.1
  intl: any
  onesignal_flutter: ^2.2.0
  shimmer: ^1.1.2
  carousel_slider: ^2.2.1
  country_code_picker: ^1.1.7
  flutter_staggered_grid_view: ^0.3.0
  sticky_headers: ^0.1.8
  pretty_qr_code: ^1.0.1
  oktoast: ^3.1.3+1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
