/// Flutter icons BestIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BestIcon
///      fonts:
///       - asset: fonts/BestIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BestIcon {
  BestIcon._();

  static const _kFontFam = 'BestIcon';
  static const String _kFontPkg = null;

  static const IconData bantuanaplikasi = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brandfavorite = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jumlahpoin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kalender = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ketentuanlayanan = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData komisi = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData livechat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifikasi = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pengaturanbahasa = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promo = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qrcode = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData royalti = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saya = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statusorder = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tentang = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tokosaya = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historywd = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
